name: build

on: [push, pull_request]

jobs:
  run-test:
    runs-on: macOS-latest
    strategy:
      matrix:
        swift-version: [5.0, 4.2, 4.0]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build config
        run: make build_config
      - name: Debug build
        run: make debug
      - name: Execute test
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run:  make test
